on: 
  push:
    branches:
      - master
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
  update:
    needs: checkout
    runs-on: self-hosted
    steps:
      - shell: bash
        run: | 
          rsync -azP --exclude '.git' --exclude '.github' /home/github/actions-runner/_work/PowerticPipesBundle/PowerticPipesBundle/ /var/www/mautic/plugins/PowerticPipesBundle
